name: 'feishu bot action'
description: 'message by Feishu bot, super tiny. run one time cost 1s. support linux macos and window, base node runner not by docker'
author: 'foxundermoon'
inputs:
  url:
    required: true
    description: 'web hook url'
  msg_type:
    required: false
    description: the msg type  https://www.feishu.cn/hc/zh-CN/articles/360024984973
    default: text
  content:
    required: true
    description: the msg content https://www.feishu.cn/hc/zh-CN/articles/360024984973

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  color: 'blue'
  icon: 'message-square'
